/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f395beffa0281508e0e9a8df0124f805)
interface __BaseEnv_Env {
	VALIDATION_BUCKET: R2Bucket;
	VALIDATION_DB: D1Database;
	GITHUB_OWNER: "R3Neer";
	GITHUB_REPO: "Mud";
	GITHUB_WORKFLOW: "validate-repo-patcher-remote.yml";
	GITHUB_REF: "main";
	GITHUB_REPOSITORY_ID: "1323036958";
	GITHUB_ALLOWED_ACTORS: "R3Neer,efferra";
	OIDC_AUDIENCE: "mud-repo-patcher-worker";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "GITHUB_REPOSITORY_ID" | "GITHUB_ALLOWED_ACTORS" | "OIDC_AUDIENCE">> {}
}
