/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dca45a9f5d64aa81ecbad0e6cceb5b1e)
interface __BaseEnv_Env {
	PROBE_BUCKET: R2Bucket;
	PROBE_ROUTE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROBE_ROUTE_SECRET">> {}
}
